### PR TITLE
Embed markdown in exported files

### LINKED ISSUE #12: Copy Embededded blocks in the exported file.
Often files got embedded from other files. It will be very helpful if the plugin can copy the embedded section in the output markdown file.

### PR DESCRIPTION
**Pull request by uroybd**
Not really proud of this code. However, this is a necessary hack. Apparently, `MarkdownView.markdownRenderer` doesn't render embeds.

My strategy is to create the embed map from the dom, match it with documents and replace it. I did some extra processing here like appending `>` at line start so it looks like a quote (that is how embed should look.

Closes #12

### CODE REVIEW

**Review by bingryan — COMMENTED** [review]
nice job

**Comment by uroybd** [comment]
> nice job

Thank you. I've noticed that attachments don't get copied if not in the same directory as the note being exported. I've solved this problem using `MetadataCache.getFirstLinkpathDest`. Would like me to push it here (since it's a minuscule thing) or in a separate PR?

**Comment by bingryan** [comment]
> > nice job
> 
> Thank you. I've noticed that attachments don't get copied if not in the same directory as the note being exported. I've solved this problem using `MetadataCache.getFirstLinkpathDest`. Would like me to push it here (since it's a minuscule thing) or in a separate PR?

new PR is better 👍

**Comment by uroybd** [comment]
Cool. I'll do that.

**Comment by bingryan** [comment]
@uroybd BTW, can fix this ci error? 

Related Issues:
#15

**Comment by uroybd** [comment]
@bingryan 

Okay, Now you can try giving permission for the first contributor.

**Comment by uroybd** [comment]
Since it is working for you and the code change is quite observable, and no real tests there to be done, perhaps you can just merge it.

**Comment by bingryan** [comment]
> Since it is working for you and the code change is quite observable, and no real tests there to be done, perhaps you can just merge it.

I changed the condition of the workflow

**Pull request merged**
